@startuml
interface "IDataStoreObject<T>"<IDataObject> {
    All : IEnumerable<T> <<get>>
    Get(key:object) : T
    Add(entity:T) : Task
    Delete(entity:T) : Task
    Edit(entity:T) : Task
}
@enduml
