@startuml
!include .\ElCazador.Test/WorkerTest.puml
!include .\ElCazador.Terminal/TerminalController.puml
!include .\ElCazador.Terminal/Program.puml
!include .\ElCazador.Worker/Worker.puml
!include .\ElCazador.Worker/Class1.puml
!include .\ElCazador.Web/Startup.puml
!include .\ElCazador.Web/Program.puml
!include .\ElCazador.Test/Web/JsonDataStoreTest.puml
!include .\ElCazador.Worker/Utils/ByteUtils.puml
!include .\ElCazador.Worker/Utils/Hex.puml
!include .\ElCazador.Worker/Utils/Networking.puml
!include .\ElCazador.Worker/Models/LogEntry.puml
!include .\ElCazador.Worker/Models/User.puml
!include .\ElCazador.Worker/Models/WorkerSettings.puml
!include .\ElCazador.Worker/Models/IPacket.puml
!include .\ElCazador.Worker/Models/IWorkerSettings.puml
!include .\ElCazador.Worker/Models/Target.puml
!include .\ElCazador.Worker/DataStore/IDataObject.puml
!include .\ElCazador.Worker/DataStore/EncryptedStringPropertyResolver.puml
!include .\ElCazador.Worker/DataStore/IDataStoreObject.puml
!include .\ElCazador.Worker/Modules/BaseModule.puml
!include .\ElCazador.Worker/Modules/IPersistantModule.puml
!include .\ElCazador.Worker/Modules/IToolModule.puml
!include .\ElCazador.Worker/Modules/IModule.puml
!include .\ElCazador.Worker/Interfaces/IWorkerController.puml
!include .\ElCazador.Worker/Interfaces/IDataStore.puml
!include .\ElCazador.Web/DataStore/JsonDataStoreObject.puml
!include .\ElCazador.Web/DataStore/JsonDataStore.puml
!include .\ElCazador.Web/Hubs/TargetHub.puml
!include .\ElCazador.Web/Hubs/UserHub.puml
!include .\ElCazador.Web/Hubs/LogHub.puml
!include .\ElCazador.Web/Worker/WebController.puml
!include .\ElCazador.Web/Controllers/HomeController.puml
!include .\ElCazador.Worker/Modules/Tools/ProcessStarter.puml
!include .\ElCazador.Worker/Modules/Tools/LsassDumpTool.puml
!include .\ElCazador.Worker/Modules/Spoofers/ISpoofer.puml
!include .\ElCazador.Worker/Modules/Spoofers/LLMNRSpoofer.puml
!include .\ElCazador.Worker/Modules/Spoofers/SpooferCore.puml
!include .\ElCazador.Worker/Modules/Spoofers/SpooferSettings.puml
!include .\ElCazador.Worker/Modules/Spoofers/Sockets.puml
!include .\ElCazador.Worker/Modules/Spoofers/BaseSpoofer.puml
!include .\ElCazador.Worker/Modules/Spoofers/NBNSSpoofer.puml
!include .\ElCazador.Worker/Modules/Servers/SMBUtils.puml
!include .\ElCazador.Worker/Modules/Servers/SMBServer.puml
!include .\ElCazador.Worker/Modules/Servers/HttpServer.puml
!include .\ElCazador.Web/Hubs/Models/DumpTarget.puml
!include .\ElCazador.Web/Hubs/Actions/UserHubActions.puml
!include .\ElCazador.Web/Hubs/Actions/TargetHubActions.puml
!include .\ElCazador.Web/Hubs/Actions/LogHubActions.puml
!include .\ElCazador.Web/Hubs/Actions/IHubAction.puml
!include .\ElCazador.Test/obj/Debug/netcoreapp2.1/ElCazador.Test.AssemblyInfo.puml
!include .\ElCazador.Test/obj/Debug/netcoreapp2.1/ElCazador.Test.Program.puml
!include .\ElCazador.Terminal/obj/Debug/netcoreapp2.1/ElCazador.Terminal.AssemblyInfo.puml
!include .\ElCazador.Worker/obj/Debug/netstandard2.0/ElCazador.Worker.AssemblyInfo.puml
!include .\ElCazador.Worker/Modules/Tools/Models/ProcessResult.puml
!include .\ElCazador.Worker/Modules/Spoofers/Models/SpooferPacket.puml
!include .\ElCazador.Worker/Modules/Spoofers/Models/NBNSPacket.puml
!include .\ElCazador.Worker/Modules/Spoofers/Models/LLMNRPacket.puml
!include .\ElCazador.Worker/Modules/Spoofers/Models/SocketType.puml
!include .\ElCazador.Worker/Modules/Servers/Models/SMB2Commands.puml
!include .\ElCazador.Worker/Modules/Servers/Models/SMB2NegotiateResponse.puml
!include .\ElCazador.Worker/Modules/Servers/Models/SMB2NTLMNegotiate.puml
!include .\ElCazador.Worker/Modules/Servers/Models/SMB2AccessDenied.puml
!include .\ElCazador.Worker/Modules/Servers/Models/HttpNTLMPacket.puml
!include .\ElCazador.Worker/Modules/Servers/Models/SMB2Header.puml
!include .\ElCazador.Worker/Modules/Servers/Models/SMBPacket.puml
!include .\ElCazador.Web/obj/Debug/netcoreapp2.1/ElCazador.Web.RazorAssemblyInfo.puml
!include .\ElCazador.Web/obj/Debug/netcoreapp2.1/ElCazador.Web.RazorTargetAssemblyInfo.puml
!include .\ElCazador.Web/obj/Debug/netcoreapp2.1/ElCazador.Web.AssemblyInfo.puml
!include .\ElCazador.Web/node_modules/node-gyp/lib/Find-VS2017.puml
!include .\ElCazador.Web/obj/Debug/netcoreapp2.1/Razor/Views/_ViewStart.g.cshtml.puml
!include .\ElCazador.Web/obj/Debug/netcoreapp2.1/Razor/Views/_ViewImports.g.cshtml.puml
!include .\ElCazador.Web/obj/Debug/netcoreapp2.1/Razor/Views/Home/Index.g.cshtml.puml
!include .\ElCazador.Web/obj/Debug/netcoreapp2.1/Razor/Views/Shared/Error.g.cshtml.puml
!include .\ElCazador.Web/obj/Debug/netcoreapp2.1/Razor/Views/Shared/_Layout.g.cshtml.puml
@enduml
