@startuml Worker-files
!include ElCazador.Worker/Worker.puml
!include ElCazador.Worker/Utils/ByteUtils.puml
!include ElCazador.Worker/Utils/Networking.puml
!include ElCazador.Worker/Models/LogEntry.puml
!include ElCazador.Worker/Models/User.puml
!include ElCazador.Worker/Models/WorkerSettings.puml
!include ElCazador.Worker/Models/IPacket.puml
!include ElCazador.Worker/Models/IWorkerSettings.puml
!include ElCazador.Worker/Models/Target.puml
!include ElCazador.Worker/DataStore/IDataObject.puml
!include ElCazador.Worker/DataStore/EncryptedStringPropertyResolver.puml
!include ElCazador.Worker/DataStore/IDataStoreObject.puml
!include ElCazador.Worker/Modules/IPersistantModule.puml
!include ElCazador.Worker/Modules/IToolModule.puml
!include ElCazador.Worker/Modules/IModule.puml
!include ElCazador.Worker/Modules/BaseModule.puml
!include ElCazador.Worker/Interfaces/IWorkerController.puml
!include ElCazador.Worker/Interfaces/IDataStore.puml
!include ElCazador.Worker/Modules/Tools/ProcessStarter.puml
!include ElCazador.Worker/Modules/Tools/LsassDumpTool.puml
!include ElCazador.Worker/Modules/Spoofers/ISpoofer.puml
!include ElCazador.Worker/Modules/Spoofers/LLMNRSpoofer.puml
!include ElCazador.Worker/Modules/Spoofers/SpooferCore.puml
!include ElCazador.Worker/Modules/Spoofers/SpooferSettings.puml
!include ElCazador.Worker/Modules/Spoofers/Sockets.puml
!include ElCazador.Worker/Modules/Spoofers/BaseSpoofer.puml
!include ElCazador.Worker/Modules/Spoofers/NBNSSpoofer.puml
!include ElCazador.Worker/Modules/Servers/SMBServer.puml
!include ElCazador.Worker/Modules/Servers/HttpServer.puml
@enduml